# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x04\x64\x61ta\"\"\n\x04\x45\x64ge\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\"\"\n\x05Graph\x12\x19\n\x05graph\x18\x01 \x03(\x0b\x32\n.data.Edge\"\x1a\n\x07GraphId\x12\x0f\n\x07graphid\x18\x01 \x01(\t\"?\n\x0cSourceTarget\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0f\n\x07graphid\x18\x03 \x01(\t\" \n\x0c\x44istResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"\"\n\x0e\x44\x65leteResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\"\"\n\x0e\x43reateResponse\x12\x10\n\x08response\x18\x01 \x01(\x03\x32\xb4\x01\n\x0fGraphOperations\x12\x32\n\x0b\x43reateGraph\x12\x0b.data.Graph\x1a\x14.data.CreateResponse\"\x00\x12\x37\n\x0bGetDistance\x12\x12.data.SourceTarget\x1a\x12.data.DistResponse\"\x00\x12\x34\n\x0b\x44\x65leteGraph\x12\r.data.GraphId\x1a\x14.data.DeleteResponse\"\x00\x62\x06proto3')



_EDGE = DESCRIPTOR.message_types_by_name['Edge']
_GRAPH = DESCRIPTOR.message_types_by_name['Graph']
_GRAPHID = DESCRIPTOR.message_types_by_name['GraphId']
_SOURCETARGET = DESCRIPTOR.message_types_by_name['SourceTarget']
_DISTRESPONSE = DESCRIPTOR.message_types_by_name['DistResponse']
_DELETERESPONSE = DESCRIPTOR.message_types_by_name['DeleteResponse']
_CREATERESPONSE = DESCRIPTOR.message_types_by_name['CreateResponse']
Edge = _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
  'DESCRIPTOR' : _EDGE,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.Edge)
  })
_sym_db.RegisterMessage(Edge)

Graph = _reflection.GeneratedProtocolMessageType('Graph', (_message.Message,), {
  'DESCRIPTOR' : _GRAPH,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.Graph)
  })
_sym_db.RegisterMessage(Graph)

GraphId = _reflection.GeneratedProtocolMessageType('GraphId', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHID,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.GraphId)
  })
_sym_db.RegisterMessage(GraphId)

SourceTarget = _reflection.GeneratedProtocolMessageType('SourceTarget', (_message.Message,), {
  'DESCRIPTOR' : _SOURCETARGET,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.SourceTarget)
  })
_sym_db.RegisterMessage(SourceTarget)

DistResponse = _reflection.GeneratedProtocolMessageType('DistResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISTRESPONSE,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.DistResponse)
  })
_sym_db.RegisterMessage(DistResponse)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETERESPONSE,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.DeleteResponse)
  })
_sym_db.RegisterMessage(DeleteResponse)

CreateResponse = _reflection.GeneratedProtocolMessageType('CreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESPONSE,
  '__module__' : 'graph_pb2'
  # @@protoc_insertion_point(class_scope:data.CreateResponse)
  })
_sym_db.RegisterMessage(CreateResponse)

_GRAPHOPERATIONS = DESCRIPTOR.services_by_name['GraphOperations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EDGE._serialized_start=21
  _EDGE._serialized_end=55
  _GRAPH._serialized_start=57
  _GRAPH._serialized_end=91
  _GRAPHID._serialized_start=93
  _GRAPHID._serialized_end=119
  _SOURCETARGET._serialized_start=121
  _SOURCETARGET._serialized_end=184
  _DISTRESPONSE._serialized_start=186
  _DISTRESPONSE._serialized_end=218
  _DELETERESPONSE._serialized_start=220
  _DELETERESPONSE._serialized_end=254
  _CREATERESPONSE._serialized_start=256
  _CREATERESPONSE._serialized_end=290
  _GRAPHOPERATIONS._serialized_start=293
  _GRAPHOPERATIONS._serialized_end=473
# @@protoc_insertion_point(module_scope)
